export const JobsData = [
  {
    id: 1,
    title: "Full Stack Engineer",
    type: "Full Time",
    company: "Google",
    location: "Lagos, Nigeria",
    status: "open",
    date: "2023-12-12",
    deadline: "2023-12-29",
    description:
      "You will be working on a team of 5 and will be working on multiple projects. You have to be a fast learner and demonstrate excellent problem solving skills.",
    salary: "100000",
  },
  {
    id: 2,
    title: "Software Engineer",
    type: "Hybrid",
    company: "Bloomberg",
    location: "Owerri, Nigeria",
    status: "open",
    date: "2023-12-12",
    deadline: "2024-02-13",
    description:
      "You should have at least 5 years of experience in the field. You will be working on a team of 5 and will be working on multiple projects. You have to be a fast learner and demonstrate excellent problem solving skills.",
    salary: "50000",
  },
  {
    id: 3,
    title: "UI/UX Designer",
    type: "Onsite",
    company: "Hossanadev",
    location: "Carliford, UK",
    status: "on hold",
    date: "2023-12-12",
    deadline: "2023-12-29",
    description:
      "You will be working on a team of 5 and will be working on multiple projects. You have to be a fast learner and demonstrate excellent problem solving skills.",
    salary: "58000",
  },
  {
    id: 4,
    title: "Backend Developer",
    type: "Remote",
    company: "Google",
    location: "Lagos",
    status: "closed",
    date: "2023-12-12",
    deadine: "2023-12-29",
    description:
      "You will be working on a team of 5 and will be working on multiple projects. You have to be a fast learner and demonstrate excellent problem solving skills.",
    salary: "106000",
  },
  {
    id: 5,
    title: "Computer Operator",
    type: "Full Time",
    company: "Oxford",
    location: "New York, USA",
    status: "open",
    date: "2023-12-12",
    deadline: "2023-12-29",
    description:
      "You will be working on a team of 5 and will be working on multiple projects. You have to be a fast learner and demonstrate excellent problem solving skills.",
    salary: "18000",
  },
  {
    id: 6,
    title: "Software Engineer",
    type: "Remote",
    company: "Google",
    location: "Lagos, Nigeria",
    status: "on hold",
    date: "2023-12-12",
    deadline: "2023-12-29",
    description:
      "You should have knowledge of JavaScript, React, and Node. You will be working on a team of 5 and will be working on multiple projects. You have to be a fast learner and demonstrate excellent problem solving skills.",
    salary: "100000",
  },
  {
    id: 7,
    title: "Devops Engineer",
    type: "Hybrid",
    company: "Google",
    location: "Berlin, Germany",
    status: "closed",
    date: "2023-12-12",
    deadline: "2023-12-29",
    description:
      "Applicants must be at least 5 years of experience in the field. Expert in working with Kubernetes, Docker, and Git. You will be working on a team of 5 and will be working on multiple projects. You have to be a fast learner and demonstrate excellent problem solving skills.",
    salary: "100000",
  },
];
