export const JobsData = [
  {
    id: 1,
    title: "Full Stack Engineer",
    type: "Full Time",
    company: "Google",
    location: "Lagos, Nigeria",
    status: "open",
    date: "2023-12-12",
    deadline: "2023-12-29",
    description:
      "You will be working on a team of 5 and will be working on multiple projects. You have to be a fast learner and demonstrate excellent problem solving skills.",
    salary: "100000",
  },
  {
    id: 2,
    title: "Software Engineer",
    type: "Hybrid",
    company: "Bloomberg",
    location: "Owerri, Nigeria",
    status: "open",
    date: "2023-12-12",
    deadline: "2024-02-13",
    description:
      "You should have at least 5 years of experience in the field. You will be working on a team of 5 and will be working on multiple projects. You have to be a fast learner and demonstrate excellent problem solving skills.",
    salary: "50000",
  },
  {
    id: 3,
    title: "UI/UX Designer",
    type: "Onsite",
    company: "Hossanadev",
    location: "Carliford, UK",
    status: "on hold",
    date: "2023-12-12",
    deadline: "2023-12-29",
    description:
      "You will be working on a team of 5 and will be working on multiple projects. You have to be a fast learner and demonstrate excellent problem solving skills.",
    salary: "58000",
  },
  {
    id: 4,
    title: "Backend Developer",
    type: "Remote",
    company: "Google",
    location: "Lagos",
    status: "closed",
    date: "2023-12-12",
    deadline: "2023-12-29",
    description:
      "You will be working on a team of 5 and will be working on multiple projects. You have to be a fast learner and demonstrate excellent problem solving skills.",
    salary: "106000",
  },
  {
    id: 5,
    title: "Computer Operator",
    type: "Full Time",
    company: "Oxford",
    location: "New York, USA",
    status: "open",
    date: "2023-12-12",
    deadline: "2023-12-29",
    description:
      "You will be working on a team of 5 and will be working on multiple projects. You have to be a fast learner and demonstrate excellent problem solving skills.",
    salary: "18000",
  },
  {
    id: 6,
    title: "Software Engineer",
    type: "Remote",
    company: "Google",
    location: "Lagos, Nigeria",
    status: "on hold",
    date: "2023-12-12",
    deadline: "2023-12-29",
    description:
      "You should have knowledge of JavaScript, React, and Node. You will be working on a team of 5 and will be working on multiple projects. You have to be a fast learner and demonstrate excellent problem solving skills.",
    salary: "100000",
  },
  {
    id: 7,
    title: "Devops Engineer",
    type: "Hybrid",
    company: "Google",
    location: "Berlin, Germany",
    status: "closed",
    date: "2023-12-12",
    deadline: "2023-12-29",
    description:
      "Applicants must be at least 5 years of experience in the field. Expert in working with Kubernetes, Docker, and Git. You will be working on a team of 5 and will be working on multiple projects. You have to be a fast learner and demonstrate excellent problem solving skills.",
    salary: "100000",
  },
  {
    id: 8,
    title: "Full Stack Engineer",
    type: "Full Time",
    company: "Google",
    location: "Lagos, Nigeria",
    status: "open",
    date: "2023-12-12",
    deadline: "2023-12-29",
    description:
      "You will be working on a team of 5 and will be working on multiple projects. You have to be a fast learner and demonstrate excellent problem solving skills.",
    salary: "100000",
  },
];

export const UsersData = [
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@me.com",
    phone: "08012345678",
    position: "Software Engineer",
    type: "Employer",
    about: "My name is John Doe. I am a software engineer. I am a full-stack developer.",
  },
  {
    id: 2,
    name: "Mary Bush",
    email: "janemary@me.com",
    phone: "08002345678",
    position: "Backend Developer",
    type: "Job seeker",
    about: "My name is Mary Bush. I am a backend developer. I am a full-stack developer.",
  },
  {
    id: 3,
    name: "Hossanadev",
    email: "hossanadev@me.com",
    phone: "08012345678",
    position: "Software Engineer",
    type: "Employer",
    about: "I am a full-stack developer. I am a full-stack developer.",
  },
  {
    id: 4,
    name: "Kate Benjamin",
    email: "katebenjamin@me.com",
    phone: "09042345678",
    position: "Frontend Developer",
    type: "Job seeker",
    about: "I am a frontend developer. I am a full-stack developer.",
  },
  {
    id: 5,
    name: "Lorenzo Joseph",
    email: "janedoe@me.com",
    phone: "08012345678",
    position: "Devops Engineer",
    type: "Employer",
    about: "I am a devops engineer. I am a full-stack developer.",
  },
  {
    id: 6,
    name: "v36ana220H",
    email: "hossanadev@me.com",
    phone: "08012345678",
    position: "Full-Stack Engineer",
    type: "Job seeker",
    about: "I am a full-stack engineer. I am a full-stack developer.",
  },
  {
    id: 7,
    name: "Christopher Moore",
    email: "chrismoore@me.com",
    phone: "09042345678",
    position: "Software Engineer",
    type: "Job seeker",
    about: "I am a software engineer. I am a full-stack developer.",
  },
  {
    id: 8,
    name: "Jane Doe",
    email: "janedoe@me.com",
    phone: "08012345678",
    position: "Software Engineer",
    type: "Employer",
    about: "I am a software engineer. I am a full-stack developer.",
  }
]